MERGE (n:Character {id: 'NvCkQmFPFo'}) SET n.name = '陆择', n.gender = '男', n.description = '男主角。灵魂穿越者，生前是个渣男', n.character_tags = '渣男, 灵魂穿越者', n.priority = 'P0';
MERGE (n:Character {id: 'NvCkQmFPFq'}) SET n.name = '陈默', n.gender = '男', n.description = '代练高手，陆择的宿主。舔狗、游戏高手、宅男，微胖，戴眼镜', n.character_tags = '舔狗, 代练, 宅男', n.priority = 'P0';
MERGE (n:Character {id: 'NvCkQmFPFs'}) SET n.name = '苏晓禾', n.gender = '女', n.description = '晨跑偶遇的运动康复师。运动、阳光、心思细腻，马甲线，马尾', n.character_tags = '运动, 阳光, 心思细腻', n.priority = 'P0';
MERGE (n:Character {id: 'NvCkQmFPFt'}) SET n.name = '林梦', n.gender = '女', n.description = '代练客户，网名「梦回峡谷」。叛逆的富家千金，毒舌，银色短发，辣妹范儿', n.character_tags = '叛逆, 富家千金, 毒舌', n.priority = 'P0';
MERGE (n:Character {id: 'NvCkQmFPFu'}) SET n.name = '沈暮雪', n.gender = '女', n.description = '星耀电竞战队经理。御姐，小资，外冷内热。眼镜，黑丝，包臀裙', n.character_tags = '御姐, 外冷内热', n.priority = 'P0';
MERGE (n:Character {id: 'NvCkQmFPFp'}) SET n.name = '伊芙', n.gender = '女', n.description = '天使，灵魂引路人，天使天然呆', n.character_tags = '天然呆', n.priority = 'P1';
MERGE (n:Character {id: 'NvCkQmFPFv'}) SET n.name = '顾盈', n.gender = '女', n.description = '陆择的一夜情对象。性感，大波浪，丰满，出场时穿着陆择的白衬衫，光腿', n.character_tags = '性感', n.priority = 'P2';
MERGE (n:Character {id: 'NvCkQmFPFw'}) SET n.name = '江烈', n.gender = '男', n.description = '星耀电竞战队队长', n.character_tags = '', n.priority = 'P2';
MERGE (n:Character {id: 'NvCkQmFPFr'}) SET n.name = '温蔓青', n.gender = '女', n.description = '陈默的前女友，绿茶婊', n.character_tags = '绿茶婊', n.priority = 'P2';
MERGE (n:Character {id: 'QP23NrFZrz'}) SET n.name = '陈念', n.gender = '女', n.description = '陈默的姐姐，关心弟弟，话痨式唠叨', n.character_tags = '话痨, 唠叨', n.priority = 'P2';
MERGE (n:Location {id: 'QP23NrFZqa'}) SET n.name = '长江大桥', n.description = '陈默跳江的地方；苏晓禾支线 D28 两人并肩跑过的护栏段';
MERGE (n:Location {id: 'QP23NrFZqb'}) SET n.name = '八楼出租屋', n.description = '陈默的住所，十几平米；爬楼梯气喘（身体缺乏锻炼）';
MERGE (n:Location {id: 'QP23NrFZqc'}) SET n.name = '南滨路', n.description = '晨跑偶遇苏晓禾的路线';
MERGE (n:Location {id: 'QP23NrFZqd'}) SET n.name = '星耀电竞基地', n.description = '星耀电竞战队训练基地，含训练馆与空场馆';
MERGE (n:Location {id: 'QP23NrFZqe'}) SET n.name = '连锁咖啡店', n.description = '沈暮雪约见陆择、邀请加入二队的另一家连锁咖啡店（区别于序章街角咖啡店）';
MERGE (n:Location {id: 'QP23NrFZqf'}) SET n.name = '西餐厅', n.description = 'Day 11 沈暮雪拉陆择吃牛排的西餐厅';
MERGE (n:Location {id: 'QP23NrFZqg'}) SET n.name = '超市', n.description = 'Day 13 苏晓禾强行拉陆择去、认真挑鸡蛋青菜牛奶的超市';
MERGE (n:Location {id: 'QP23NrFZqh'}) SET n.name = '登山步道', n.description = 'Day 15 爬山地点';
MERGE (n:Location {id: 'QP23NrFZqi'}) SET n.name = '地铁', n.description = 'Day 15 傍晚返程，苏晓禾睡着靠过来的地铁';
MERGE (n:Location {id: 'QP23NrFZqj'}) SET n.name = '漫展会场', n.description = 'Day 16 林梦拉陆择去的漫展';
MERGE (n:Location {id: 'QP23NrFZqk'}) SET n.name = '林梦家', n.description = '超级大平层，空荡无人像酒店';
MERGE (n:Location {id: 'QP23NrFZql'}) SET n.name = '路边摊', n.description = 'Day 18 把沈暮雪辣出眼泪的路边摊；沈暮雪支线 D27 夜宵同一家';
MERGE (n:Location {id: 'QP23NrFZqm'}) SET n.name = '康复中心', n.description = '苏晓禾工作的地方，运动康复';
MERGE (n:Event {id: 'QP23NrFZqo'}) SET n.title = '姐姐来电', n.time = 'Day 0 深夜', n.description = '分支 A（再想想）：选择再等等，姐姐陈念的电话恰好打了进来，主线继续', n.type = '转折';
MERGE (n:Event {id: 'QP23NrFZqp'}) SET n.title = '发现转账删除温蔓青', n.time = 'Day 0 深夜', n.description = '陆择在转账记录里发现陈默给温蔓青的 66666，直接果断删除温蔓青微信——「别人的债，不接」（已共识：无分支的果断动作，原选择节点取消）', n.type = '行动';
MERGE (n:Event {id: 'QP23NrFZqq'}) SET n.title = '理发买衣吃面', n.time = 'Day 1', n.description = '为猎艳收拾自己：理发（Tony 一句「你多久没打理过自己了」给出摆烂刻度）、平价店买衣、重庆小面——余额只剩几十块，吃太快干噎出眼泪，身体在食物面前发抖；发现待交付代练订单，生存压力有了形状；晚上交单一单，手感好到藏不住', n.type = '行动';
MERGE (n:Event {id: 'QP23NrFZqr'}) SET n.title = '林梦点单翻盘', n.time = 'Day 2', n.description = '老客户林梦「最后相信你一次」的点单——被翻盘打脸当场真香变回小迷妹；她没马上退语音，自顾自聊了半小时八卦，下线前说「你声音听起来精神多了」——陆择第一次「不想让人失望」', n.type = '交流';
MERGE (n:Event {id: 'QP23NrFZqs'}) SET n.title = '陈念探望', n.time = 'Day 3', n.description = '陈念杀到出租屋：打量弟弟、摸到空冰箱开骂、塞满冻饺排骨汤、唠叨中红了眼；临走检查燃气、在碗底压一沓现金；她发现弟弟好像有点不一样了——晚饭多吃了一碗。陆择的落点是羡慕：陈默有人惦记', n.type = '交流';
MERGE (n:Event {id: 'QP23NrFZqt'}) SET n.title = '晨跑搭讪碰壁', n.time = 'Day 4', n.description = '陆择按渣男剧本搭讪苏晓禾——话术、展现身材；她全程公事公办：「你这样跑膝盖要废」，开始纠正姿势。渣男方法论第一次碰壁，剧本失效（动因：误读任务为「帮陈默找个漂亮女朋友」）', n.type = '交流';
MERGE (n:Event {id: 'QP23NrFZqu'}) SET n.title = '直播准备日', n.time = 'Day 4', n.description = '林梦提议直播；设备事故三连：麦克风静音、游戏闪退、远程大小姐口气指挥；升级配置的钱林梦出——「本小姐投资你，以后直播赚了十倍还我」', n.type = '行动';
MERGE (n:Event {id: 'QP23NrFZqv'}) SET n.title = '生存算账日', n.time = 'Day 5', n.description = '算陈默的人生账：代练收入、平台抽成、房租、欠林梦的设备款、碗底的现金、温蔓青的 66666 能要回多少——接下这个人生的人是他，擦屁股的也只能是他；收下姐姐的钱、收拾旧物、定三个闹钟，生活回到正轨', n.type = '转折';
MERGE (n:Event {id: 'QP23NrFZqw'}) SET n.title = '首播破万', n.time = 'Day 6', n.description = '首场直播峰值 12000；下播后对着黑掉的屏幕发了一会儿呆——极轻的身份酸涩；当晚收到沈暮雪直球挖人私信（扫榜早标记了这个胜率异常的路人大神）', n.type = '行动';
MERGE (n:Event {id: 'QP23NrFZqx'}) SET n.title = '星耀试训冲突', n.time = 'Day 7', n.description = '个人碾压但团队配合稀烂；双立场对峙——江烈的怒有职业道理，陆择的懒散有底层逻辑；错的是试训本身是沈暮雪单方面越级邀请；收场是观察期：「下周一再来，输一局滚蛋」', n.type = '交流';
MERGE (n:Event {id: 'QP23NrFZqy'}) SET n.title = '晨跑双向确认', n.time = 'Day 8', n.description = '再遇苏晓禾是偶遇不是安排；他默默按她说的改了姿势，她在身后看了几秒把配速放慢半拍陪他跑完——两个人都不说破。治愈线第一次双向确认', n.type = '交流';
MERGE (n:Event {id: 'QP23NrFZqz'}) SET n.title = '温蔓青质问电话', n.time = 'Day 9', n.description = '温蔓青反常来电质问为什么删她微信——语气不是愧疚是兴师问罪；陆择一句平淡的话挡回挂断；不翻旧账不心软不回收 66666——对过去的切割第一次接受外部检验，他通过了', n.type = '交流';
MERGE (n:Event {id: 'QP23NrFZr0'}) SET n.title = '沈暮雪邀约二队', n.time = 'Day 10', n.description = '另一家连锁咖啡店约见，邀请加入二队——带前置条件「二队需要稳定上线时间，你要先能把生活过成规律的」；她是在江烈反对的情况下继续推这件事——外冷内热，落在行动上', n.type = '转折';
MERGE (n:Event {id: 'QP23NrFZr1'}) SET n.title = '西餐厅牛排', n.time = 'Day 11', n.description = '沈暮雪加微信后看到签名「想吃肉」，拉他去西餐厅吃牛排', n.type = '行动';
MERGE (n:Event {id: 'QP23NrFZr2'}) SET n.title = '深夜双排CP起哄', n.time = 'Day 12', n.description = '林梦日：深夜双排，观众起哄组 CP；她嘴硬「谁跟他在一起」却全程没下麦——第一次在游戏里被人护着，遭遇不敢承认的关系曝光时刻', n.type = '交流';
MERGE (n:Event {id: 'QP23NrFZr3'}) SET n.title = '遇雨避入出租屋', n.time = 'Day 13 上午', n.description = '跑步突然下雨，两人躲进陈默的出租屋', n.type = '行动';
MERGE (n:Event {id: 'QP23NrFZr4'}) SET n.title = '超市挑食材', n.time = 'Day 13 下午', n.description = '苏晓禾发现冰箱只有可乐和泡面，强行拉他去超市，认真挑鸡蛋、青菜、牛奶——他吐槽像老夫老妻，她耳朵红了装没听见', n.type = '行动';
MERGE (n:Event {id: 'QP23NrFZr5'}) SET n.title = '林梦对喷弹幕', n.time = 'Day 14', n.description = '林梦当房管和阴阳怪气的弹幕对喷（重点照顾 Day 12 起哄的那批观众）', n.type = '交流';
MERGE (n:Event {id: 'QP23NrFZr6'}) SET n.title = '爬山', n.time = 'Day 15', n.description = '他幻想的是瑜伽服，实际是休闲服', n.type = '行动';
MERGE (n:Event {id: 'QP23NrFZr7'}) SET n.title = '地铁靠肩', n.time = 'Day 15 傍晚', n.description = '地铁返程，苏晓禾累得睡着，头轻轻靠了过来', n.type = '交流';
MERGE (n:Event {id: 'QP23NrFZr8'}) SET n.title = '漫展情侣角色', n.time = 'Day 16', n.description = '林梦拉他去漫展——提前买通抽签、备好两套情侣角色（做局），他恰好抽到对应角色；她高兴得偷偷拍照，现场紧张得手心冒汗生怕被看穿', n.type = '行动';
MERGE (n:Event {id: 'QP23NrFZr9'}) SET n.title = '大平层夜谈', n.time = 'Day 16 晚上', n.description = '送林梦回家——超级大平层却没人、很安静、像酒店；她一边拆零食一边说「我小时候发烧，家里只有保姆」，发朋友圈「今天超幸运」；他心里嘀咕「这几个……算弱者吗」', n.type = '交流';
MERGE (n:Event {id: 'QP23NrFZrA'}) SET n.title = '生病反转照顾', n.time = 'Day 17', n.description = '他生病发烧苏晓禾送吃的；他反过来识破她也感冒硬扛着来——第一次有人照顾她，她愣住；单向温暖升级为双向治愈', n.type = '状态变化';
MERGE (n:Event {id: 'QP23NrFZrB'}) SET n.title = '路边摊辣哭', n.time = 'Day 18', n.description = '他拉沈暮雪去路边摊，把她辣出眼泪', n.type = '行动';
MERGE (n:Event {id: 'QP23NrFZrC'}) SET n.title = '偷看约晚餐', n.time = 'Day 19', n.description = '偷偷去苏晓禾工作的康复中心看她，约了晚餐', n.type = '行动';
MERGE (n:Event {id: 'QP23NrFZrD'}) SET n.title = '空场馆真心话', n.time = 'Day 20', n.description = '观察期考核通过、二队邀约正式落定；赛后她难得卸下经理身份，两人在空场馆聊真心话——他问「为什么是我」，她答「因为我赌你」；他第一次没用套路回话', n.type = '交流';
MERGE (n:Event {id: 'QP23NrFZrE'}) SET n.title = '静场日', n.time = 'Day 21', n.description = '深夜合上电脑，手却自己点开游戏图标，赢一局输一局凌晨三点才停手；翻聊天记录看到温蔓青朋友圈（换新男朋友）。没有事件没有女主，只有这个身体原本的样子：用游戏和舔狗行为填满自己的空壳', n.type = '状态变化';
MERGE (n:Event {id: 'QP23NrFZrF'}) SET n.title = '三个未接来电', n.time = 'Day 22', n.description = '三个未接来电——苏晓禾问周末跑步路线、林梦说抢到了漫展志愿名额、沈暮雪邀他观礼二队首秀；玩家回拨谁，就是选谁', n.type = '转折';
MERGE (n:Event {id: 'QP23NrFZrG'}) SET n.title = '入职二队报到', n.time = 'Day 23', n.description = '正式入职二队与新队友磨合——生面孔、新环境，代练习惯和团队节奏处处磕碰', n.type = '行动';
MERGE (n:Event {id: 'QP23NrFZrH'}) SET n.title = '首次正规训练赛', n.time = 'Day 24', n.description = '第一次上正规训练赛：报点、复盘、按战术自我约束——Day 7 那句「凭什么惯着你」在这里被打脸，他主动学团队配合', n.type = '行动';
MERGE (n:Event {id: 'QP23NrFZrI'}) SET n.title = '江烈督导认可', n.time = 'Day 25', n.description = '江烈来督导，两人 Day 7 的对峙变成认可（「你这人还行」级别的承认，不煽情）', n.type = '交流';
MERGE (n:Event {id: 'QP23NrFZrJ'}) SET n.title = '双面切换心疼', n.time = 'Day 26', n.description = '沈暮雪白天经理、晚上恋人双面切换；他第一次看到她两头烧的状态——心疼但不声张，把夜宵默默放在她桌上', n.type = '交流';
MERGE (n:Event {id: 'QP23NrFZrK'}) SET n.title = '恋爱日常缓冲', n.time = 'Day 27', n.description = '训练间隙的便当、下班后的夜宵摊（回收 Day 18 把她辣出眼泪的那家），默契升温', n.type = '行动';
MERGE (n:Event {id: 'QP23NrFZrL'}) SET n.title = '首秀落后翻盘', n.time = 'Day 28', n.description = '首秀日落后翻盘；赛后他说「你赌赢了」，她说「是我们一起赌赢的」', n.type = '行动';
MERGE (n:Event {id: 'QP23NrFZrM'}) SET n.title = '电竞路定调', n.time = 'Day 29', n.description = '关系定调——两人确定一起走这条电竞路（直通后日谈世界冠军起点）', n.type = '状态变化';
MERGE (n:Event {id: 'QP23NrFZrN'}) SET n.title = '留学计划砸下', n.time = 'Day 23', n.description = '父母直接甩留学安排：学校、中介都已联系好只剩签字，三分钟说完挂断，连吵的资格都不给她——伤害她的从来不是管束，是不在乎', n.type = '转折';
MERGE (n:Event {id: 'QP23NrFZrO'}) SET n.title = '借酒吐露留学事', n.time = 'Day 24', n.description = '她表面答应背地里睡不着，深夜拉他双排，借着酒劲把这事倒了出来——大小姐第一次在人前卸掉毒舌', n.type = '交流';
MERGE (n:Event {id: 'QP23NrFZrP'}) SET n.title = '看接单平台', n.time = 'Day 25', n.description = '他没劝留也没劝签，只带她去看自己接单的平台，看普通主播和小团队怎么起步——用陈默代练圈的见识，让她看到「可行的路」而不只是「想做的心」', n.type = '行动';
MERGE (n:Event {id: 'QP23NrFZrQ'}) SET n.title = '决定拒签', n.time = 'Day 26', n.description = '她决定拒签，打电话问「如果失败了你会不会笑话我」；他没用话术说了实话：失败了也比替别人活强。她说「这话真不像你」，他说「以前那个才是装的呢」', n.type = '交流';
MERGE (n:Event {id: 'QP23NrFZrR'}) SET n.title = '为自己做功课', n.time = 'Day 27', n.description = '她开始准备自己的事（游戏工作室/战队陪练方向调研，不一定是主播），拉他帮忙列计划——大小姐第一次为自己的决定做功课', n.type = '行动';
MERGE (n:Event {id: 'QP23NrFZrS'}) SET n.title = '拒签快递寄出', n.time = 'Day 28', n.description = '拒签快递寄出的那天，她在中介楼下的马路边站了很久，他陪着；寄出一刻她跳起来捶了他一下说「完了，后悔了」，又自己笑场', n.type = '行动';
MERGE (n:Event {id: 'QP23NrFZrT'}) SET n.title = '出租屋庆祝', n.time = 'Day 29', n.description = '她在他那间小出租屋里拆零食庆祝——比起 Day 16 的空旷大平层，十几平米有人、有声音、有烟火气；关系定调：她第一次觉得某个地方像家', n.type = '状态变化';
MERGE (n:Event {id: 'QP23NrFZrU'}) SET n.title = '便当堵路线', n.time = 'Day 23', n.description = '他早起做第一份便当堵在她的跑步路线上——第一次反向照顾；她愣住又嘴硬「谁要吃这个」', n.type = '行动';
MERGE (n:Event {id: 'QP23NrFZrV'}) SET n.title = '强行换她休息', n.time = 'Day 24', n.description = '她感冒未愈还想着带他训练，他强行换她休息，自己翻她以前记的姿势纠正笔记照着练——照顾者第一次被人放在心上', n.type = '行动';
MERGE (n:Event {id: 'QP23NrFZrW'}) SET n.title = '充数见父母', n.time = 'Day 25', n.description = '她父母突然来市里，她临时拉他去充数；饭桌上他第一次演「别人家的男孩」，也第一次在家庭饭桌上不觉得刺痛（呼应 Day 3 陈念戏的「我也想要家」）', n.type = '交流';
MERGE (n:Event {id: 'QP23NrFZrX'}) SET n.title = '互见底牌', n.time = 'Day 26', n.description = '他坦白便当是照她笔记学的、咸了淡了都是照着改——两人互见底牌：她的照顾上瘾、他的刻意学习，谁也没笑话谁', n.type = '交流';
MERGE (n:Event {id: 'QP23NrFZrY'}) SET n.title = '陪加班看评估', n.time = 'Day 27', n.description = '陪她加班，看她给病人做康复评估——他第一次看到她「照顾别人上瘾」的职业形态，没有打断，下班时接走了人', n.type = '行动';
MERGE (n:Event {id: 'QP23NrFZrZ'}) SET n.title = '大桥夜跑', n.time = 'Day 28', n.description = '两人并肩跑过 Day 0 陈默跳江的那段护栏——谁也没提，但都放慢了脚步（预演后日谈画面）', n.type = '行动';
MERGE (n:Event {id: 'QP23NrFZra'}) SET n.title = '主动约会定调', n.time = 'Day 29', n.description = '父母走后她主动约他——关系定调，不再是谁照顾谁，是两个人', n.type = '状态变化';
MERGE (n:Event {id: 'QP23NrFZrb'}) SET n.title = '伊芙现身三揭晓', n.time = 'Day 30', n.description = '深夜久违的天使伊芙现身宣告试炼结束；三揭晓一口气兑现——真规则：第一个弱者就是宿主陈默本人，拯救是心灵上的；陈默在场：意识从未离开，30 天一切都看在眼里；好处：「你救了一个人的心，也救了你自己」，罪债勾销', n.type = '转折';
MERGE (n:Event {id: 'QP23NrFZrc'}) SET n.title = '陆择赴下一试炼', n.time = 'Day 30', n.description = '陆择离开陈默的身体前往下一个试炼；身后是被他改变的人生（按所选女主线各自收尾，接后日谈）', n.type = '转折';
MERGE (n:Event {id: 'QP23NrFZrd'}) SET n.title = '后日谈·苏晓禾线', n.time = '后日谈', n.description = '陈默从游戏代练回归正常生活，两人并肩跑过大桥，恍然与过去的自己擦肩', n.type = '状态变化';
MERGE (n:Event {id: 'QP23NrFZre'}) SET n.title = '后日谈·林梦线', n.time = '后日谈', n.description = '陈默成为人气很高的大主播，林梦是他背后支持他的人（「赚了十倍还我」在此兑现）', n.type = '状态变化';
MERGE (n:Event {id: 'QP23NrFZrf'}) SET n.title = '后日谈·沈暮雪线', n.time = '后日谈', n.description = '陈默加入战队，夺得世界冠军', n.type = '状态变化';
MERGE (n:Info {id: 'QP23NrFZrh'}) SET n.title = '试炼真规则', n.content = '「拯救 6 个弱者」的真规则：第一章的弱者是宿主陈默本人，几个女主都不是弱者。Day 0-30 陆择始终不知道这一点，他的瞎猜方向全是误读，直到 Day 21-30 才揭晓', n.knowledge_level = 1;
MERGE (n:Info {id: 'QP23NrFZri'}) SET n.title = '拯救的定义', n.content = '心灵拯救而非物理拯救——不是把他从栏杆外拉回来那一下，而是把他从「不想活」的心境里拉回来。规律生活、与姐姐和解、被三个人真心喜欢、体验被在乎，都是给陈默灵魂的药', n.knowledge_level = 1;
MERGE (n:Info {id: 'QP23NrFZrj'}) SET n.title = '陈默意识从未离开', n.content = '陈默的意识从未离开身体，这 30 天陆择做的一切他都看在眼里（包括全部的恋爱）。陆择离开后，留下来的是一个被治愈过的陈默', n.knowledge_level = 1;
MERGE (n:Info {id: 'QP23NrFZrk'}) SET n.title = '试炼好处', n.content = '开场欠下的钩子兑现：「你救了一个人的心，也救了你自己」——渣男陆择的灵魂罪债勾销，可以安稳离开；上辈子欠下的债这辈子还清（镜像暗线收束）', n.knowledge_level = 1;
MERGE (n:Info {id: 'QP23NrFZrl'}) SET n.title = '全书结构', n.content = '序章+六章，「拯救 6 个弱者」= 每章一个弱者、一个新宿主——第一章救陈默，后续五章陆择各穿越一个新宿主、救一个新弱者。Day 30 收尾「陆择赴下一试炼」即出口', n.knowledge_level = 1;
MERGE (n:Info {id: 'QP23NrFZrm'}) SET n.title = '女主对换魂不知情', n.content = '女主对换魂不知情、永不告知——Day 30 陆择离开后，陈默带着这 30 天的共同记忆继续与所选女主的关系。读者知道她不知道，留一层温柔的酸涩', n.knowledge_level = 1;
MERGE (n:Info {id: 'QP23NrFZrn'}) SET n.title = '陆择误读任务', n.content = '伊芙没说清规则，陆择从「拯救弱者」自行推断出「帮陈默找个漂亮女朋友」，于是渣男式的主动出击（Day 4 晨跑搭讪的动因）；任务进度零反馈使瞎猜成为 Day 0-21 的常态', n.knowledge_level = 1;
MERGE (n:Info {id: 'QP23NrFZro'}) SET n.title = '伊芙零反馈设定', n.content = '伊芙 Day 0-21 不露面、任务进度零反馈——陆择只能瞎猜谁算「弱者」；这为 Day 21-30 揭晓真规则时埋下「原来他猜错了」的伏笔', n.knowledge_level = 1;
MERGE (n:Info {id: 'QP23NrFZrp'}) SET n.title = 'Day1-21零选择电影段', n.content = 'Day 0 的【删除微信/留着】选择节点已取消（改为无分支的果断动作）；Day 1-21 全程零选择就是一部电影，玩家选择留到 Day 22 三选一才爆发', n.knowledge_level = 1;
MERGE (n:Info {id: 'QP23NrFZrq'}) SET n.title = '温蔓青66666不回收', n.content = '主线内不回收——它的功能是塑造陈默的惨与舔狗史，Day 5 算账已兑现；追债/撕逼戏会破坏治愈基调，留白即「他也放下了」的态度', n.knowledge_level = 2;
MERGE (n:Info {id: 'QP23NrFZrr'}) SET n.title = '三选一机制', n.content = '三通未接来电各有内容——各带一句语音或短信邀约（苏晓禾问周末跑步路线、林梦说抢到了漫展志愿名额、沈暮雪邀他观礼二队首秀），玩家回拨谁就是选谁；未选的两个号码从此音讯渐稀，不写撕破脸，留白给二周目', n.knowledge_level = 1;
MERGE (n:Info {id: 'QP23NrFZrs'}) SET n.title = '林梦漫展做局', n.content = '「恰好抽到」是林梦做的局——她提前买通了抽签、备好两套情侣角色，算准他会被抽到；漫展现场她紧张得手心冒汗，生怕被看穿。与 Day 12 嘴硬不下麦是同一性格：想靠近，只敢绕弯', n.knowledge_level = 2;
MERGE (n:Info {id: 'QP23NrFZrt'}) SET n.title = '苏晓禾软肋', n.content = '照顾别人上瘾——她从小照顾生病/忙碌缺席的父母，习惯当照顾者，没人问过她累不累', n.knowledge_level = 2;
MERGE (n:Info {id: 'QP23NrFZru'}) SET n.title = '沈暮雪软肋', n.content = '「没人押过她」的孤注——女经理、非职业选手出身、选人眼光怪，一路被质疑；她越级邀请陆择，是因为在榜单上看到了当年那个没人肯赌的自己。「押没人押的人」与陆择的「拯救弱者」任务构成同构暗线', n.knowledge_level = 2;
MERGE (n:Info {id: 'QP23NrFZrv'}) SET n.title = '渣男镜像', n.content = '上一世同时吊多个女孩、这一世同时暖三个人的同构；Day 11-20 陆择对此毫无自觉，纯然享受暖三人的状态——自我厌恶与反思全部留到 Day 22 三选一之后。镜像只从上帝视角可见，是玩家独享的讽刺，不进主角内心', n.knowledge_level = 2;
MERGE (n:Info {id: 'QP23NrFZrw'}) SET n.title = '巅峰赛单排爬榜', n.content = '一个无车队、无公会的单排 ID 悄悄爬进巅峰赛排行榜前列——Day 6 沈暮雪扫榜时早标记了这个胜率异常的路人大神（挖人私信的由来）', n.knowledge_level = 2;
MERGE (n:Info {id: 'QP23NrFZrx'}) SET n.title = '设备款关系钩子', n.content = '直播设备升级的钱是林梦出的——「本小姐投资你，以后直播赚了十倍还我」；欠人情是关系钩子，为 Day 11-20 漫展戏的服从度提供经济解释；林梦线后日谈兑现十倍回收', n.knowledge_level = 2;
MERGE (n:Info {id: 'QP23NrFZry'}) SET n.title = '观察期默认通过', n.content = '第二次试训（Day 10 之前的周一）江烈没再骂人，只是赛后多看了他两眼——观察期的默认通过，为二队邀请做铺垫', n.knowledge_level = 2;
MERGE (n:Info {id: 'NvCkQmFPGb'}) SET n.title = '灵魂穿越者的控制与选择', n.content = '陆择可以直接控制宿主的言行；在他拿不准、两难、情绪冲突的节点，这份犹豫会演出为玩家面前的选择项——选择的不是替陈默做主，而是陆择自己内心的天平', n.knowledge_level = 1;
MERGE (n:Choice {id: 'QP23NrFZqn'}) SET n.name = '三选一', n.description = '三个未接来电后，选择一位女主回拨，进入该线恋爱剧情（全书第一次真正的选择爆发）', n.time = 'Day 22';
MATCH (a:Character {id: 'QP23NrFZrz'}), (b:Character {id: 'NvCkQmFPFq'}) MERGE (a)-[:relation {type: '亲属', detail: '姐弟'}]->(b);
MATCH (a:Character {id: 'QP23NrFZrz'}), (b:Event {id: 'QP23NrFZqo'}) MERGE (a)-[:involved {role: '当事人', detail: '来电'}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFq'}), (b:Event {id: 'QP23NrFZqo'}) MERGE (a)-[:involved {role: '当事人', detail: '接听'}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFq'}), (b:Event {id: 'QP23NrFZqp'}) MERGE (a)-[:involved {role: '当事人', detail: ''}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFr'}), (b:Event {id: 'QP23NrFZqp'}) MERGE (a)-[:involved {role: '涉及', detail: '被删除微信'}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFq'}), (b:Event {id: 'QP23NrFZqq'}) MERGE (a)-[:involved {role: '当事人', detail: ''}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFq'}), (b:Event {id: 'QP23NrFZqr'}) MERGE (a)-[:involved {role: '当事人', detail: '代练接单'}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFt'}), (b:Event {id: 'QP23NrFZqr'}) MERGE (a)-[:involved {role: '当事人', detail: '点单客户'}]->(b);
MATCH (a:Character {id: 'QP23NrFZrz'}), (b:Event {id: 'QP23NrFZqs'}) MERGE (a)-[:involved {role: '当事人', detail: ''}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFq'}), (b:Event {id: 'QP23NrFZqs'}) MERGE (a)-[:involved {role: '当事人', detail: ''}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFq'}), (b:Event {id: 'QP23NrFZqt'}) MERGE (a)-[:involved {role: '当事人', detail: '搭讪'}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFs'}), (b:Event {id: 'QP23NrFZqt'}) MERGE (a)-[:involved {role: '参与者', detail: '纠正跑步姿势'}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFq'}), (b:Event {id: 'QP23NrFZqu'}) MERGE (a)-[:involved {role: '当事人', detail: ''}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFt'}), (b:Event {id: 'QP23NrFZqu'}) MERGE (a)-[:involved {role: '参与者', detail: '提议直播并投资设备'}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFq'}), (b:Event {id: 'QP23NrFZqv'}) MERGE (a)-[:involved {role: '当事人', detail: ''}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFq'}), (b:Event {id: 'QP23NrFZqw'}) MERGE (a)-[:involved {role: '当事人', detail: ''}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFq'}), (b:Event {id: 'QP23NrFZqx'}) MERGE (a)-[:involved {role: '当事人', detail: '试训选手'}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFw'}), (b:Event {id: 'QP23NrFZqx'}) MERGE (a)-[:involved {role: '当事人', detail: '战队队长'}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFu'}), (b:Event {id: 'QP23NrFZqx'}) MERGE (a)-[:involved {role: '涉及', detail: '单方面越级邀请的发起人'}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFq'}), (b:Event {id: 'QP23NrFZqy'}) MERGE (a)-[:involved {role: '当事人', detail: ''}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFs'}), (b:Event {id: 'QP23NrFZqy'}) MERGE (a)-[:involved {role: '当事人', detail: '放慢配速相陪'}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFq'}), (b:Event {id: 'QP23NrFZqz'}) MERGE (a)-[:involved {role: '当事人', detail: '被质问'}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFr'}), (b:Event {id: 'QP23NrFZqz'}) MERGE (a)-[:involved {role: '当事人', detail: '兴师问罪'}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFq'}), (b:Event {id: 'QP23NrFZr0'}) MERGE (a)-[:involved {role: '当事人', detail: ''}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFu'}), (b:Event {id: 'QP23NrFZr0'}) MERGE (a)-[:involved {role: '当事人', detail: '发出邀请'}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFq'}), (b:Event {id: 'QP23NrFZr1'}) MERGE (a)-[:involved {role: '当事人', detail: ''}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFu'}), (b:Event {id: 'QP23NrFZr1'}) MERGE (a)-[:involved {role: '当事人', detail: ''}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFq'}), (b:Event {id: 'QP23NrFZr2'}) MERGE (a)-[:involved {role: '当事人', detail: ''}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFt'}), (b:Event {id: 'QP23NrFZr2'}) MERGE (a)-[:involved {role: '当事人', detail: '嘴硬不下麦'}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFq'}), (b:Event {id: 'QP23NrFZr3'}) MERGE (a)-[:involved {role: '当事人', detail: ''}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFs'}), (b:Event {id: 'QP23NrFZr3'}) MERGE (a)-[:involved {role: '当事人', detail: ''}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFq'}), (b:Event {id: 'QP23NrFZr4'}) MERGE (a)-[:involved {role: '当事人', detail: ''}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFs'}), (b:Event {id: 'QP23NrFZr4'}) MERGE (a)-[:involved {role: '当事人', detail: ''}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFt'}), (b:Event {id: 'QP23NrFZr5'}) MERGE (a)-[:involved {role: '当事人', detail: '房管'}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFq'}), (b:Event {id: 'QP23NrFZr5'}) MERGE (a)-[:involved {role: '参与者', detail: '直播中'}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFq'}), (b:Event {id: 'QP23NrFZr6'}) MERGE (a)-[:involved {role: '当事人', detail: ''}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFs'}), (b:Event {id: 'QP23NrFZr6'}) MERGE (a)-[:involved {role: '当事人', detail: ''}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFq'}), (b:Event {id: 'QP23NrFZr7'}) MERGE (a)-[:involved {role: '当事人', detail: ''}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFs'}), (b:Event {id: 'QP23NrFZr7'}) MERGE (a)-[:involved {role: '当事人', detail: '睡着靠过来'}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFq'}), (b:Event {id: 'QP23NrFZr8'}) MERGE (a)-[:involved {role: '当事人', detail: ''}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFt'}), (b:Event {id: 'QP23NrFZr8'}) MERGE (a)-[:involved {role: '当事人', detail: '做局者'}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFq'}), (b:Event {id: 'QP23NrFZr9'}) MERGE (a)-[:involved {role: '当事人', detail: ''}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFt'}), (b:Event {id: 'QP23NrFZr9'}) MERGE (a)-[:involved {role: '当事人', detail: ''}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFq'}), (b:Event {id: 'QP23NrFZrA'}) MERGE (a)-[:involved {role: '当事人', detail: '发烧'}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFs'}), (b:Event {id: 'QP23NrFZrA'}) MERGE (a)-[:involved {role: '当事人', detail: '硬扛感冒来照顾'}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFq'}), (b:Event {id: 'QP23NrFZrB'}) MERGE (a)-[:involved {role: '当事人', detail: ''}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFu'}), (b:Event {id: 'QP23NrFZrB'}) MERGE (a)-[:involved {role: '当事人', detail: '被辣出眼泪'}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFq'}), (b:Event {id: 'QP23NrFZrC'}) MERGE (a)-[:involved {role: '当事人', detail: ''}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFs'}), (b:Event {id: 'QP23NrFZrC'}) MERGE (a)-[:involved {role: '涉及', detail: '被偷看'}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFq'}), (b:Event {id: 'QP23NrFZrD'}) MERGE (a)-[:involved {role: '当事人', detail: ''}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFu'}), (b:Event {id: 'QP23NrFZrD'}) MERGE (a)-[:involved {role: '当事人', detail: ''}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFq'}), (b:Event {id: 'QP23NrFZrE'}) MERGE (a)-[:involved {role: '当事人', detail: '原状态的阴影回归'}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFq'}), (b:Event {id: 'QP23NrFZrF'}) MERGE (a)-[:involved {role: '当事人', detail: ''}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFs'}), (b:Event {id: 'QP23NrFZrF'}) MERGE (a)-[:involved {role: '涉及', detail: '来电一'}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFt'}), (b:Event {id: 'QP23NrFZrF'}) MERGE (a)-[:involved {role: '涉及', detail: '来电二'}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFu'}), (b:Event {id: 'QP23NrFZrF'}) MERGE (a)-[:involved {role: '涉及', detail: '来电三'}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFq'}), (b:Event {id: 'QP23NrFZrG'}) MERGE (a)-[:involved {role: '当事人', detail: ''}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFu'}), (b:Event {id: 'QP23NrFZrG'}) MERGE (a)-[:involved {role: '当事人', detail: ''}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFq'}), (b:Event {id: 'QP23NrFZrH'}) MERGE (a)-[:involved {role: '当事人', detail: ''}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFu'}), (b:Event {id: 'QP23NrFZrH'}) MERGE (a)-[:involved {role: '参与者', detail: ''}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFq'}), (b:Event {id: 'QP23NrFZrI'}) MERGE (a)-[:involved {role: '当事人', detail: ''}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFw'}), (b:Event {id: 'QP23NrFZrI'}) MERGE (a)-[:involved {role: '当事人', detail: '督导'}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFu'}), (b:Event {id: 'QP23NrFZrI'}) MERGE (a)-[:involved {role: '涉及', detail: ''}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFq'}), (b:Event {id: 'QP23NrFZrJ'}) MERGE (a)-[:involved {role: '当事人', detail: ''}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFu'}), (b:Event {id: 'QP23NrFZrJ'}) MERGE (a)-[:involved {role: '当事人', detail: '两头烧'}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFq'}), (b:Event {id: 'QP23NrFZrK'}) MERGE (a)-[:involved {role: '当事人', detail: ''}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFu'}), (b:Event {id: 'QP23NrFZrK'}) MERGE (a)-[:involved {role: '当事人', detail: ''}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFq'}), (b:Event {id: 'QP23NrFZrL'}) MERGE (a)-[:involved {role: '当事人', detail: ''}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFu'}), (b:Event {id: 'QP23NrFZrL'}) MERGE (a)-[:involved {role: '当事人', detail: ''}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFq'}), (b:Event {id: 'QP23NrFZrM'}) MERGE (a)-[:involved {role: '当事人', detail: ''}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFu'}), (b:Event {id: 'QP23NrFZrM'}) MERGE (a)-[:involved {role: '当事人', detail: ''}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFq'}), (b:Event {id: 'QP23NrFZrN'}) MERGE (a)-[:involved {role: '参与者', detail: '倾听'}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFt'}), (b:Event {id: 'QP23NrFZrN'}) MERGE (a)-[:involved {role: '当事人', detail: '被安排留学'}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFq'}), (b:Event {id: 'QP23NrFZrO'}) MERGE (a)-[:involved {role: '参与者', detail: ''}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFt'}), (b:Event {id: 'QP23NrFZrO'}) MERGE (a)-[:involved {role: '当事人', detail: ''}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFq'}), (b:Event {id: 'QP23NrFZrP'}) MERGE (a)-[:involved {role: '当事人', detail: '带看平台'}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFt'}), (b:Event {id: 'QP23NrFZrP'}) MERGE (a)-[:involved {role: '当事人', detail: ''}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFq'}), (b:Event {id: 'QP23NrFZrQ'}) MERGE (a)-[:involved {role: '当事人', detail: '说实话'}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFt'}), (b:Event {id: 'QP23NrFZrQ'}) MERGE (a)-[:involved {role: '当事人', detail: '决定拒签'}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFq'}), (b:Event {id: 'QP23NrFZrR'}) MERGE (a)-[:involved {role: '参与者', detail: '帮忙列计划'}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFt'}), (b:Event {id: 'QP23NrFZrR'}) MERGE (a)-[:involved {role: '当事人', detail: ''}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFq'}), (b:Event {id: 'QP23NrFZrS'}) MERGE (a)-[:involved {role: '参与者', detail: '陪伴'}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFt'}), (b:Event {id: 'QP23NrFZrS'}) MERGE (a)-[:involved {role: '当事人', detail: '寄出拒签'}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFq'}), (b:Event {id: 'QP23NrFZrT'}) MERGE (a)-[:involved {role: '参与者', detail: ''}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFt'}), (b:Event {id: 'QP23NrFZrT'}) MERGE (a)-[:involved {role: '当事人', detail: ''}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFq'}), (b:Event {id: 'QP23NrFZrU'}) MERGE (a)-[:involved {role: '当事人', detail: '做便当'}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFs'}), (b:Event {id: 'QP23NrFZrU'}) MERGE (a)-[:involved {role: '当事人', detail: ''}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFq'}), (b:Event {id: 'QP23NrFZrV'}) MERGE (a)-[:involved {role: '当事人', detail: '强行换她休息'}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFs'}), (b:Event {id: 'QP23NrFZrV'}) MERGE (a)-[:involved {role: '当事人', detail: ''}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFq'}), (b:Event {id: 'QP23NrFZrW'}) MERGE (a)-[:involved {role: '当事人', detail: '充数男友'}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFs'}), (b:Event {id: 'QP23NrFZrW'}) MERGE (a)-[:involved {role: '当事人', detail: ''}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFq'}), (b:Event {id: 'QP23NrFZrX'}) MERGE (a)-[:involved {role: '当事人', detail: '坦白'}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFs'}), (b:Event {id: 'QP23NrFZrX'}) MERGE (a)-[:involved {role: '当事人', detail: ''}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFq'}), (b:Event {id: 'QP23NrFZrY'}) MERGE (a)-[:involved {role: '参与者', detail: '陪加班'}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFs'}), (b:Event {id: 'QP23NrFZrY'}) MERGE (a)-[:involved {role: '当事人', detail: ''}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFq'}), (b:Event {id: 'QP23NrFZrZ'}) MERGE (a)-[:involved {role: '当事人', detail: ''}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFs'}), (b:Event {id: 'QP23NrFZrZ'}) MERGE (a)-[:involved {role: '当事人', detail: ''}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFq'}), (b:Event {id: 'QP23NrFZra'}) MERGE (a)-[:involved {role: '当事人', detail: ''}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFs'}), (b:Event {id: 'QP23NrFZra'}) MERGE (a)-[:involved {role: '当事人', detail: '主动邀约'}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFo'}), (b:Event {id: 'QP23NrFZrb'}) MERGE (a)-[:involved {role: '当事人', detail: '被告知者'}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFp'}), (b:Event {id: 'QP23NrFZrb'}) MERGE (a)-[:involved {role: '当事人', detail: '宣告试炼结束'}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFq'}), (b:Event {id: 'QP23NrFZrb'}) MERGE (a)-[:involved {role: '涉及', detail: '意识在场'}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFo'}), (b:Event {id: 'QP23NrFZrc'}) MERGE (a)-[:involved {role: '当事人', detail: '离开宿主'}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFp'}), (b:Event {id: 'QP23NrFZrc'}) MERGE (a)-[:involved {role: '参与者', detail: '引路'}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFq'}), (b:Event {id: 'QP23NrFZrc'}) MERGE (a)-[:involved {role: '涉及', detail: '被留下的人'}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFq'}), (b:Event {id: 'QP23NrFZrd'}) MERGE (a)-[:involved {role: '当事人', detail: ''}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFs'}), (b:Event {id: 'QP23NrFZrd'}) MERGE (a)-[:involved {role: '当事人', detail: ''}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFq'}), (b:Event {id: 'QP23NrFZre'}) MERGE (a)-[:involved {role: '当事人', detail: ''}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFt'}), (b:Event {id: 'QP23NrFZre'}) MERGE (a)-[:involved {role: '当事人', detail: ''}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFq'}), (b:Event {id: 'QP23NrFZrf'}) MERGE (a)-[:involved {role: '当事人', detail: ''}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFu'}), (b:Event {id: 'QP23NrFZrf'}) MERGE (a)-[:involved {role: '当事人', detail: ''}]->(b);
MATCH (a:Event {id: 'QP23NrFZqo'}), (b:Location {id: 'QP23NrFZqa'}) MERGE (a)-[:occurred_at {detail: '接电话处'}]->(b);
MATCH (a:Event {id: 'QP23NrFZqp'}), (b:Location {id: 'QP23NrFZqb'}) MERGE (a)-[:occurred_at {detail: ''}]->(b);
MATCH (a:Event {id: 'QP23NrFZqs'}), (b:Location {id: 'QP23NrFZqb'}) MERGE (a)-[:occurred_at {detail: ''}]->(b);
MATCH (a:Event {id: 'QP23NrFZqt'}), (b:Location {id: 'QP23NrFZqc'}) MERGE (a)-[:occurred_at {detail: '晨跑路线'}]->(b);
MATCH (a:Event {id: 'QP23NrFZqu'}), (b:Location {id: 'QP23NrFZqb'}) MERGE (a)-[:occurred_at {detail: ''}]->(b);
MATCH (a:Event {id: 'QP23NrFZqv'}), (b:Location {id: 'QP23NrFZqb'}) MERGE (a)-[:occurred_at {detail: ''}]->(b);
MATCH (a:Event {id: 'QP23NrFZqw'}), (b:Location {id: 'QP23NrFZqb'}) MERGE (a)-[:occurred_at {detail: ''}]->(b);
MATCH (a:Event {id: 'QP23NrFZqx'}), (b:Location {id: 'QP23NrFZqd'}) MERGE (a)-[:occurred_at {detail: '试训场'}]->(b);
MATCH (a:Event {id: 'QP23NrFZqy'}), (b:Location {id: 'QP23NrFZqc'}) MERGE (a)-[:occurred_at {detail: ''}]->(b);
MATCH (a:Event {id: 'QP23NrFZr0'}), (b:Location {id: 'QP23NrFZqe'}) MERGE (a)-[:occurred_at {detail: '约见'}]->(b);
MATCH (a:Event {id: 'QP23NrFZr1'}), (b:Location {id: 'QP23NrFZqf'}) MERGE (a)-[:occurred_at {detail: ''}]->(b);
MATCH (a:Event {id: 'QP23NrFZr3'}), (b:Location {id: 'QP23NrFZqb'}) MERGE (a)-[:occurred_at {detail: '避雨处'}]->(b);
MATCH (a:Event {id: 'QP23NrFZr4'}), (b:Location {id: 'QP23NrFZqg'}) MERGE (a)-[:occurred_at {detail: ''}]->(b);
MATCH (a:Event {id: 'QP23NrFZr6'}), (b:Location {id: 'QP23NrFZqh'}) MERGE (a)-[:occurred_at {detail: ''}]->(b);
MATCH (a:Event {id: 'QP23NrFZr7'}), (b:Location {id: 'QP23NrFZqi'}) MERGE (a)-[:occurred_at {detail: '返程'}]->(b);
MATCH (a:Event {id: 'QP23NrFZr8'}), (b:Location {id: 'QP23NrFZqj'}) MERGE (a)-[:occurred_at {detail: ''}]->(b);
MATCH (a:Event {id: 'QP23NrFZr9'}), (b:Location {id: 'QP23NrFZqk'}) MERGE (a)-[:occurred_at {detail: ''}]->(b);
MATCH (a:Event {id: 'QP23NrFZrA'}), (b:Location {id: 'QP23NrFZqb'}) MERGE (a)-[:occurred_at {detail: ''}]->(b);
MATCH (a:Event {id: 'QP23NrFZrB'}), (b:Location {id: 'QP23NrFZql'}) MERGE (a)-[:occurred_at {detail: ''}]->(b);
MATCH (a:Event {id: 'QP23NrFZrC'}), (b:Location {id: 'QP23NrFZqm'}) MERGE (a)-[:occurred_at {detail: '苏晓禾工作地'}]->(b);
MATCH (a:Event {id: 'QP23NrFZrD'}), (b:Location {id: 'QP23NrFZqd'}) MERGE (a)-[:occurred_at {detail: '空场馆'}]->(b);
MATCH (a:Event {id: 'QP23NrFZrE'}), (b:Location {id: 'QP23NrFZqb'}) MERGE (a)-[:occurred_at {detail: ''}]->(b);
MATCH (a:Event {id: 'QP23NrFZrF'}), (b:Location {id: 'QP23NrFZqb'}) MERGE (a)-[:occurred_at {detail: ''}]->(b);
MATCH (a:Event {id: 'QP23NrFZrG'}), (b:Location {id: 'QP23NrFZqd'}) MERGE (a)-[:occurred_at {detail: ''}]->(b);
MATCH (a:Event {id: 'QP23NrFZrH'}), (b:Location {id: 'QP23NrFZqd'}) MERGE (a)-[:occurred_at {detail: ''}]->(b);
MATCH (a:Event {id: 'QP23NrFZrI'}), (b:Location {id: 'QP23NrFZqd'}) MERGE (a)-[:occurred_at {detail: ''}]->(b);
MATCH (a:Event {id: 'QP23NrFZrJ'}), (b:Location {id: 'QP23NrFZqd'}) MERGE (a)-[:occurred_at {detail: ''}]->(b);
MATCH (a:Event {id: 'QP23NrFZrK'}), (b:Location {id: 'QP23NrFZql'}) MERGE (a)-[:occurred_at {detail: '夜宵摊'}]->(b);
MATCH (a:Event {id: 'QP23NrFZrL'}), (b:Location {id: 'QP23NrFZqd'}) MERGE (a)-[:occurred_at {detail: '首秀'}]->(b);
MATCH (a:Event {id: 'QP23NrFZrT'}), (b:Location {id: 'QP23NrFZqb'}) MERGE (a)-[:occurred_at {detail: '庆祝'}]->(b);
MATCH (a:Event {id: 'QP23NrFZrU'}), (b:Location {id: 'QP23NrFZqc'}) MERGE (a)-[:occurred_at {detail: '跑步路线'}]->(b);
MATCH (a:Event {id: 'QP23NrFZrY'}), (b:Location {id: 'QP23NrFZqm'}) MERGE (a)-[:occurred_at {detail: ''}]->(b);
MATCH (a:Event {id: 'QP23NrFZrZ'}), (b:Location {id: 'QP23NrFZqa'}) MERGE (a)-[:occurred_at {detail: '并肩跑过护栏段'}]->(b);
MATCH (a:Event {id: 'QP23NrFZrb'}), (b:Location {id: 'QP23NrFZqb'}) MERGE (a)-[:occurred_at {detail: '深夜现身'}]->(b);
MATCH (a:Event {id: 'QP23NrFZrd'}), (b:Location {id: 'QP23NrFZqa'}) MERGE (a)-[:occurred_at {detail: '并肩跑过大桥'}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFq'}), (b:Location {id: 'QP23NrFZqb'}) MERGE (a)-[:at {type: '居住', detail: 'Day 0-30 及后日谈'}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFs'}), (b:Location {id: 'QP23NrFZqm'}) MERGE (a)-[:at {type: '工作', detail: '运动康复师'}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFw'}), (b:Location {id: 'QP23NrFZqd'}) MERGE (a)-[:at {type: '工作', detail: '战队队长'}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFu'}), (b:Location {id: 'QP23NrFZqd'}) MERGE (a)-[:at {type: '工作', detail: '战队经理'}]->(b);
MATCH (a:Character {id: 'NvCkQmFPFt'}), (b:Location {id: 'QP23NrFZqk'}) MERGE (a)-[:at {type: '居住', detail: '超级大平层'}]->(b);
MATCH (a) WHERE a.id = 'NvCkQmFPFp' MATCH (b:Info {id: 'QP23NrFZrh'}) MERGE (a)-[:link {type: '涉及', detail: '她定下的规则'}]->(b);
MATCH (a) WHERE a.id = 'QP23NrFZrb' MATCH (b:Info {id: 'QP23NrFZri'}) MERGE (a)-[:link {type: '涉及', detail: ''}]->(b);
MATCH (a) WHERE a.id = 'NvCkQmFPFq' MATCH (b:Info {id: 'QP23NrFZrj'}) MERGE (a)-[:link {type: '涉及', detail: ''}]->(b);
MATCH (a) WHERE a.id = 'QP23NrFZrb' MATCH (b:Info {id: 'QP23NrFZrk'}) MERGE (a)-[:link {type: '涉及', detail: ''}]->(b);
MATCH (a) WHERE a.id = 'NvCkQmFPFz' MATCH (b:Info {id: 'QP23NrFZrl'}) MERGE (a)-[:link {type: '涉及', detail: '六个试炼的世界框架'}]->(b);
MATCH (a) WHERE a.id = 'NvCkQmFPFq' MATCH (b:Info {id: 'QP23NrFZrm'}) MERGE (a)-[:link {type: '涉及', detail: '带着共同记忆继续关系'}]->(b);
MATCH (a) WHERE a.id = 'NvCkQmFPFo' MATCH (b:Info {id: 'QP23NrFZrn'}) MERGE (a)-[:link {type: '涉及', detail: '灵魂层认知'}]->(b);
MATCH (a) WHERE a.id = 'NvCkQmFPFp' MATCH (b:Info {id: 'QP23NrFZro'}) MERGE (a)-[:link {type: '涉及', detail: ''}]->(b);
MATCH (a) WHERE a.id = 'NvCkQmFPFq' MATCH (b:Info {id: 'QP23NrFZrp'}) MERGE (a)-[:link {type: '涉及', detail: '主角叙事节奏设定'}]->(b);
MATCH (a) WHERE a.id = 'NvCkQmFPFr' MATCH (b:Info {id: 'QP23NrFZrq'}) MERGE (a)-[:link {type: '涉及', detail: ''}]->(b);
MATCH (a) WHERE a.id = 'QP23NrFZrF' MATCH (b:Info {id: 'QP23NrFZrr'}) MERGE (a)-[:link {type: '涉及', detail: ''}]->(b);
MATCH (a) WHERE a.id = 'QP23NrFZr8' MATCH (b:Info {id: 'QP23NrFZrs'}) MERGE (a)-[:link {type: '涉及', detail: ''}]->(b);
MATCH (a) WHERE a.id = 'NvCkQmFPFs' MATCH (b:Info {id: 'QP23NrFZrt'}) MERGE (a)-[:link {type: '涉及', detail: ''}]->(b);
MATCH (a) WHERE a.id = 'NvCkQmFPFu' MATCH (b:Info {id: 'QP23NrFZru'}) MERGE (a)-[:link {type: '涉及', detail: ''}]->(b);
MATCH (a) WHERE a.id = 'NvCkQmFPFo' MATCH (b:Info {id: 'QP23NrFZrv'}) MERGE (a)-[:link {type: '涉及', detail: '上帝视角独享'}]->(b);
MATCH (a) WHERE a.id = 'QP23NrFZqr' MATCH (b:Info {id: 'QP23NrFZrw'}) MERGE (a)-[:link {type: '涉及', detail: 'Day 2 埋点'}]->(b);
MATCH (a) WHERE a.id = 'QP23NrFZqu' MATCH (b:Info {id: 'QP23NrFZrx'}) MERGE (a)-[:link {type: '涉及', detail: ''}]->(b);
MATCH (a) WHERE a.id = 'QP23NrFZqx' MATCH (b:Info {id: 'QP23NrFZry'}) MERGE (a)-[:link {type: '涉及', detail: ''}]->(b);
MATCH (a:Event {id: 'NvCkQmFPG0'}), (b:Event {id: 'QP23NrFZqp'}) MERGE (a)-[:evt_relation {type: '先后', detail: 'Day 0 深夜'}]->(b);
MATCH (a:Event {id: 'QP23NrFZqp'}), (b:Event {id: 'QP23NrFZqq'}) MERGE (a)-[:evt_relation {type: '先后', detail: ''}]->(b);
MATCH (a:Event {id: 'QP23NrFZqq'}), (b:Event {id: 'QP23NrFZqr'}) MERGE (a)-[:evt_relation {type: '先后', detail: ''}]->(b);
MATCH (a:Event {id: 'QP23NrFZqr'}), (b:Event {id: 'QP23NrFZqs'}) MERGE (a)-[:evt_relation {type: '先后', detail: ''}]->(b);
MATCH (a:Event {id: 'QP23NrFZqs'}), (b:Event {id: 'QP23NrFZqt'}) MERGE (a)-[:evt_relation {type: '先后', detail: ''}]->(b);
MATCH (a:Event {id: 'QP23NrFZqt'}), (b:Event {id: 'QP23NrFZqu'}) MERGE (a)-[:evt_relation {type: '先后', detail: ''}]->(b);
MATCH (a:Event {id: 'QP23NrFZqu'}), (b:Event {id: 'QP23NrFZqv'}) MERGE (a)-[:evt_relation {type: '先后', detail: ''}]->(b);
MATCH (a:Event {id: 'QP23NrFZqv'}), (b:Event {id: 'QP23NrFZqw'}) MERGE (a)-[:evt_relation {type: '先后', detail: ''}]->(b);
MATCH (a:Event {id: 'QP23NrFZqw'}), (b:Event {id: 'QP23NrFZqx'}) MERGE (a)-[:evt_relation {type: '先后', detail: ''}]->(b);
MATCH (a:Event {id: 'QP23NrFZqx'}), (b:Event {id: 'QP23NrFZqy'}) MERGE (a)-[:evt_relation {type: '先后', detail: ''}]->(b);
MATCH (a:Event {id: 'QP23NrFZqy'}), (b:Event {id: 'QP23NrFZqz'}) MERGE (a)-[:evt_relation {type: '先后', detail: ''}]->(b);
MATCH (a:Event {id: 'QP23NrFZqz'}), (b:Event {id: 'QP23NrFZr0'}) MERGE (a)-[:evt_relation {type: '先后', detail: ''}]->(b);
MATCH (a:Event {id: 'QP23NrFZr0'}), (b:Event {id: 'QP23NrFZr1'}) MERGE (a)-[:evt_relation {type: '先后', detail: ''}]->(b);
MATCH (a:Event {id: 'QP23NrFZr1'}), (b:Event {id: 'QP23NrFZr2'}) MERGE (a)-[:evt_relation {type: '先后', detail: ''}]->(b);
MATCH (a:Event {id: 'QP23NrFZr2'}), (b:Event {id: 'QP23NrFZr3'}) MERGE (a)-[:evt_relation {type: '先后', detail: ''}]->(b);
MATCH (a:Event {id: 'QP23NrFZr3'}), (b:Event {id: 'QP23NrFZr4'}) MERGE (a)-[:evt_relation {type: '先后', detail: ''}]->(b);
MATCH (a:Event {id: 'QP23NrFZr4'}), (b:Event {id: 'QP23NrFZr5'}) MERGE (a)-[:evt_relation {type: '先后', detail: ''}]->(b);
MATCH (a:Event {id: 'QP23NrFZr5'}), (b:Event {id: 'QP23NrFZr6'}) MERGE (a)-[:evt_relation {type: '先后', detail: ''}]->(b);
MATCH (a:Event {id: 'QP23NrFZr6'}), (b:Event {id: 'QP23NrFZr7'}) MERGE (a)-[:evt_relation {type: '先后', detail: ''}]->(b);
MATCH (a:Event {id: 'QP23NrFZr7'}), (b:Event {id: 'QP23NrFZr8'}) MERGE (a)-[:evt_relation {type: '先后', detail: ''}]->(b);
MATCH (a:Event {id: 'QP23NrFZr8'}), (b:Event {id: 'QP23NrFZr9'}) MERGE (a)-[:evt_relation {type: '先后', detail: ''}]->(b);
MATCH (a:Event {id: 'QP23NrFZr9'}), (b:Event {id: 'QP23NrFZrA'}) MERGE (a)-[:evt_relation {type: '先后', detail: ''}]->(b);
MATCH (a:Event {id: 'QP23NrFZrA'}), (b:Event {id: 'QP23NrFZrB'}) MERGE (a)-[:evt_relation {type: '先后', detail: ''}]->(b);
MATCH (a:Event {id: 'QP23NrFZrB'}), (b:Event {id: 'QP23NrFZrC'}) MERGE (a)-[:evt_relation {type: '先后', detail: ''}]->(b);
MATCH (a:Event {id: 'QP23NrFZrC'}), (b:Event {id: 'QP23NrFZrD'}) MERGE (a)-[:evt_relation {type: '先后', detail: ''}]->(b);
MATCH (a:Event {id: 'QP23NrFZrD'}), (b:Event {id: 'QP23NrFZrE'}) MERGE (a)-[:evt_relation {type: '先后', detail: ''}]->(b);
MATCH (a:Event {id: 'QP23NrFZrE'}), (b:Event {id: 'QP23NrFZrF'}) MERGE (a)-[:evt_relation {type: '先后', detail: ''}]->(b);
MATCH (a:Event {id: 'QP23NrFZrG'}), (b:Event {id: 'QP23NrFZrH'}) MERGE (a)-[:evt_relation {type: '先后', detail: ''}]->(b);
MATCH (a:Event {id: 'QP23NrFZrH'}), (b:Event {id: 'QP23NrFZrI'}) MERGE (a)-[:evt_relation {type: '先后', detail: ''}]->(b);
MATCH (a:Event {id: 'QP23NrFZrI'}), (b:Event {id: 'QP23NrFZrJ'}) MERGE (a)-[:evt_relation {type: '先后', detail: ''}]->(b);
MATCH (a:Event {id: 'QP23NrFZrJ'}), (b:Event {id: 'QP23NrFZrK'}) MERGE (a)-[:evt_relation {type: '先后', detail: ''}]->(b);
MATCH (a:Event {id: 'QP23NrFZrK'}), (b:Event {id: 'QP23NrFZrL'}) MERGE (a)-[:evt_relation {type: '先后', detail: ''}]->(b);
MATCH (a:Event {id: 'QP23NrFZrL'}), (b:Event {id: 'QP23NrFZrM'}) MERGE (a)-[:evt_relation {type: '先后', detail: ''}]->(b);
MATCH (a:Event {id: 'QP23NrFZrN'}), (b:Event {id: 'QP23NrFZrO'}) MERGE (a)-[:evt_relation {type: '先后', detail: ''}]->(b);
MATCH (a:Event {id: 'QP23NrFZrO'}), (b:Event {id: 'QP23NrFZrP'}) MERGE (a)-[:evt_relation {type: '先后', detail: ''}]->(b);
MATCH (a:Event {id: 'QP23NrFZrP'}), (b:Event {id: 'QP23NrFZrQ'}) MERGE (a)-[:evt_relation {type: '先后', detail: ''}]->(b);
MATCH (a:Event {id: 'QP23NrFZrQ'}), (b:Event {id: 'QP23NrFZrR'}) MERGE (a)-[:evt_relation {type: '先后', detail: ''}]->(b);
MATCH (a:Event {id: 'QP23NrFZrR'}), (b:Event {id: 'QP23NrFZrS'}) MERGE (a)-[:evt_relation {type: '先后', detail: ''}]->(b);
MATCH (a:Event {id: 'QP23NrFZrS'}), (b:Event {id: 'QP23NrFZrT'}) MERGE (a)-[:evt_relation {type: '先后', detail: ''}]->(b);
MATCH (a:Event {id: 'QP23NrFZrU'}), (b:Event {id: 'QP23NrFZrV'}) MERGE (a)-[:evt_relation {type: '先后', detail: ''}]->(b);
MATCH (a:Event {id: 'QP23NrFZrV'}), (b:Event {id: 'QP23NrFZrW'}) MERGE (a)-[:evt_relation {type: '先后', detail: ''}]->(b);
MATCH (a:Event {id: 'QP23NrFZrW'}), (b:Event {id: 'QP23NrFZrX'}) MERGE (a)-[:evt_relation {type: '先后', detail: ''}]->(b);
MATCH (a:Event {id: 'QP23NrFZrX'}), (b:Event {id: 'QP23NrFZrY'}) MERGE (a)-[:evt_relation {type: '先后', detail: ''}]->(b);
MATCH (a:Event {id: 'QP23NrFZrY'}), (b:Event {id: 'QP23NrFZrZ'}) MERGE (a)-[:evt_relation {type: '先后', detail: ''}]->(b);
MATCH (a:Event {id: 'QP23NrFZrZ'}), (b:Event {id: 'QP23NrFZra'}) MERGE (a)-[:evt_relation {type: '先后', detail: ''}]->(b);
MATCH (a:Event {id: 'QP23NrFZrM'}), (b:Event {id: 'QP23NrFZrb'}) MERGE (a)-[:evt_relation {type: '先后', detail: ''}]->(b);
MATCH (a:Event {id: 'QP23NrFZrT'}), (b:Event {id: 'QP23NrFZrb'}) MERGE (a)-[:evt_relation {type: '先后', detail: ''}]->(b);
MATCH (a:Event {id: 'QP23NrFZra'}), (b:Event {id: 'QP23NrFZrb'}) MERGE (a)-[:evt_relation {type: '先后', detail: ''}]->(b);
MATCH (a:Event {id: 'QP23NrFZrb'}), (b:Event {id: 'QP23NrFZrc'}) MERGE (a)-[:evt_relation {type: '因果', detail: '试炼结束'}]->(b);
MATCH (a:Event {id: 'QP23NrFZrc'}), (b:Event {id: 'QP23NrFZrd'}) MERGE (a)-[:evt_relation {type: '先后', detail: '苏晓禾线收尾'}]->(b);
MATCH (a:Event {id: 'QP23NrFZrc'}), (b:Event {id: 'QP23NrFZre'}) MERGE (a)-[:evt_relation {type: '先后', detail: '林梦线收尾'}]->(b);
MATCH (a:Event {id: 'QP23NrFZrc'}), (b:Event {id: 'QP23NrFZrf'}) MERGE (a)-[:evt_relation {type: '先后', detail: '沈暮雪线收尾'}]->(b);
MATCH (a:Event {id: 'QP23NrFZqo'}), (b:Event {id: 'QP23NrFZqp'}) MERGE (a)-[:evt_relation {type: '先后', detail: '分支 A 后同夜'}]->(b);
MATCH (a:Event {id: 'QP23NrFZrF'}), (b:Choice {id: 'QP23NrFZqn'}) MERGE (a)-[:presents]->(b);
MATCH (a:Choice {id: 'OdraDmqprU'}), (b:Event {id: 'QP23NrFZqo'}) MERGE (a)-[:option {label: '再想想', leads_to_ending: false}]->(b);
MATCH (a:Choice {id: 'QP23NrFZqn'}), (b:Event {id: 'QP23NrFZrU'}) MERGE (a)-[:option {label: '选苏晓禾（回拨：周末跑步路线）', leads_to_ending: false}]->(b);
MATCH (a:Choice {id: 'QP23NrFZqn'}), (b:Event {id: 'QP23NrFZrN'}) MERGE (a)-[:option {label: '选林梦（回拨：漫展志愿名额）', leads_to_ending: false}]->(b);
MATCH (a:Choice {id: 'QP23NrFZqn'}), (b:Event {id: 'QP23NrFZrG'}) MERGE (a)-[:option {label: '选沈暮雪（回拨：观礼二队首秀）', leads_to_ending: false}]->(b);
