// Step 1：19 个默认 Spot（kind=default）+ part_of 边 —— 窗口前执行，新旧边并存
MERGE (sp:Spot {name:'八楼出租屋-未细分'}) ON CREATE SET sp.id='R6YcFfBMWG', sp.kind='default', sp.description='';
MERGE (sp:Spot {name:'登山步道-未细分'}) ON CREATE SET sp.id='R6YcFfBMWH', sp.kind='default', sp.description='';
MERGE (sp:Spot {name:'地铁-未细分'}) ON CREATE SET sp.id='R6YcFfBMWI', sp.kind='default', sp.description='';
MERGE (sp:Spot {name:'服装店-未细分'}) ON CREATE SET sp.id='R6YcFfBMWJ', sp.kind='default', sp.description='';
MERGE (sp:Spot {name:'街角咖啡店-未细分'}) ON CREATE SET sp.id='R6YcFfBMWK', sp.kind='default', sp.description='';
MERGE (sp:Spot {name:'康复中心-未细分'}) ON CREATE SET sp.id='R6YcFfBMWL', sp.kind='default', sp.description='';
MERGE (sp:Spot {name:'连锁咖啡店-未细分'}) ON CREATE SET sp.id='R6YcFfBMWM', sp.kind='default', sp.description='';
MERGE (sp:Spot {name:'林梦家-未细分'}) ON CREATE SET sp.id='R6YcFfBMWN', sp.kind='default', sp.description='';
MERGE (sp:Spot {name:'理发店-未细分'}) ON CREATE SET sp.id='R6YcFfBMWO', sp.kind='default', sp.description='';
MERGE (sp:Spot {name:'路边摊-未细分'}) ON CREATE SET sp.id='R6YcFfBMWP', sp.kind='default', sp.description='';
MERGE (sp:Spot {name:'马路-未细分'}) ON CREATE SET sp.id='R6YcFfBMWQ', sp.kind='default', sp.description='';
MERGE (sp:Spot {name:'漫展会场-未细分'}) ON CREATE SET sp.id='R6YcFfBMWR', sp.kind='default', sp.description='';
MERGE (sp:Spot {name:'南滨路-未细分'}) ON CREATE SET sp.id='R6YcFfBMWS', sp.kind='default', sp.description='';
MERGE (sp:Spot {name:'灵魂夹缝-未细分'}) ON CREATE SET sp.id='R6YcFfBMWT', sp.kind='default', sp.description='';
MERGE (sp:Spot {name:'酒店-未细分'}) ON CREATE SET sp.id='R6YcFfBMWU', sp.kind='default', sp.description='';
MERGE (sp:Spot {name:'超市-未细分'}) ON CREATE SET sp.id='R6YcFfBMWV', sp.kind='default', sp.description='';
MERGE (sp:Spot {name:'西餐厅-未细分'}) ON CREATE SET sp.id='R6YcFfBMWW', sp.kind='default', sp.description='';
MERGE (sp:Spot {name:'星耀电竞基地-未细分'}) ON CREATE SET sp.id='R6YcFfBMWX', sp.kind='default', sp.description='';
MERGE (sp:Spot {name:'长江大桥-未细分'}) ON CREATE SET sp.id='R6YcFfBMWY', sp.kind='default', sp.description='';
MATCH (sp:Spot {id:'R6YcFfBMWG'}), (l:Location {name:'八楼出租屋'}) MERGE (sp)-[r:part_of]->(l) ON CREATE SET r.sync=false;
MATCH (sp:Spot {id:'R6YcFfBMWH'}), (l:Location {name:'登山步道'}) MERGE (sp)-[r:part_of]->(l) ON CREATE SET r.sync=false;
MATCH (sp:Spot {id:'R6YcFfBMWI'}), (l:Location {name:'地铁'}) MERGE (sp)-[r:part_of]->(l) ON CREATE SET r.sync=false;
MATCH (sp:Spot {id:'R6YcFfBMWJ'}), (l:Location {name:'服装店'}) MERGE (sp)-[r:part_of]->(l) ON CREATE SET r.sync=false;
MATCH (sp:Spot {id:'R6YcFfBMWK'}), (l:Location {name:'街角咖啡店'}) MERGE (sp)-[r:part_of]->(l) ON CREATE SET r.sync=false;
MATCH (sp:Spot {id:'R6YcFfBMWL'}), (l:Location {name:'康复中心'}) MERGE (sp)-[r:part_of]->(l) ON CREATE SET r.sync=false;
MATCH (sp:Spot {id:'R6YcFfBMWM'}), (l:Location {name:'连锁咖啡店'}) MERGE (sp)-[r:part_of]->(l) ON CREATE SET r.sync=false;
MATCH (sp:Spot {id:'R6YcFfBMWN'}), (l:Location {name:'林梦家'}) MERGE (sp)-[r:part_of]->(l) ON CREATE SET r.sync=false;
MATCH (sp:Spot {id:'R6YcFfBMWO'}), (l:Location {name:'理发店'}) MERGE (sp)-[r:part_of]->(l) ON CREATE SET r.sync=false;
MATCH (sp:Spot {id:'R6YcFfBMWP'}), (l:Location {name:'路边摊'}) MERGE (sp)-[r:part_of]->(l) ON CREATE SET r.sync=false;
MATCH (sp:Spot {id:'R6YcFfBMWQ'}), (l:Location {name:'马路'}) MERGE (sp)-[r:part_of]->(l) ON CREATE SET r.sync=false;
MATCH (sp:Spot {id:'R6YcFfBMWR'}), (l:Location {name:'漫展会场'}) MERGE (sp)-[r:part_of]->(l) ON CREATE SET r.sync=false;
MATCH (sp:Spot {id:'R6YcFfBMWS'}), (l:Location {name:'南滨路'}) MERGE (sp)-[r:part_of]->(l) ON CREATE SET r.sync=false;
MATCH (sp:Spot {id:'R6YcFfBMWT'}), (l:Location {name:'灵魂夹缝'}) MERGE (sp)-[r:part_of]->(l) ON CREATE SET r.sync=false;
MATCH (sp:Spot {id:'R6YcFfBMWU'}), (l:Location {name:'酒店'}) MERGE (sp)-[r:part_of]->(l) ON CREATE SET r.sync=false;
MATCH (sp:Spot {id:'R6YcFfBMWV'}), (l:Location {name:'超市'}) MERGE (sp)-[r:part_of]->(l) ON CREATE SET r.sync=false;
MATCH (sp:Spot {id:'R6YcFfBMWW'}), (l:Location {name:'西餐厅'}) MERGE (sp)-[r:part_of]->(l) ON CREATE SET r.sync=false;
MATCH (sp:Spot {id:'R6YcFfBMWX'}), (l:Location {name:'星耀电竞基地'}) MERGE (sp)-[r:part_of]->(l) ON CREATE SET r.sync=false;
MATCH (sp:Spot {id:'R6YcFfBMWY'}), (l:Location {name:'长江大桥'}) MERGE (sp)-[r:part_of]->(l) ON CREATE SET r.sync=false;
