// 原子窗口：15 个 zone Spot + part_of 边（单场景 7 + 八楼出租屋 4 + 星耀电竞基地 4）
MERGE (sp:Spot {name:'长江大桥-护栏段'}) ON CREATE SET sp.id='R6YcFfBMWZ', sp.kind='zone', sp.description='大桥护栏段步道';
MERGE (sp:Spot {name:'南滨路-滨江步道'}) ON CREATE SET sp.id='R6YcFfBMWa', sp.kind='zone', sp.description='滨江步道';
MERGE (sp:Spot {name:'马路-路口'}) ON CREATE SET sp.id='R6YcFfBMWb', sp.kind='zone', sp.description='街口路口';
MERGE (sp:Spot {name:'街角咖啡店-点餐台'}) ON CREATE SET sp.id='R6YcFfBMWc', sp.kind='zone', sp.description='咖啡店点餐台';
MERGE (sp:Spot {name:'酒店-客房'}) ON CREATE SET sp.id='R6YcFfBMWd', sp.kind='zone', sp.description='酒店客房';
MERGE (sp:Spot {name:'理发店-剪发区'}) ON CREATE SET sp.id='R6YcFfBMWe', sp.kind='zone', sp.description='理发店剪发位';
MERGE (sp:Spot {name:'连锁咖啡店-座位区'}) ON CREATE SET sp.id='R6YcFfBMWf', sp.kind='zone', sp.description='咖啡店座位区';
MERGE (sp:Spot {name:'八楼出租屋-电脑桌区'}) ON CREATE SET sp.id='R6YcFfBMWg', sp.kind='zone', sp.description='电脑桌直播位（设备更新前后两版本）';
MERGE (sp:Spot {name:'八楼出租屋-厨房餐区'}) ON CREATE SET sp.id='R6YcFfBMWh', sp.kind='zone', sp.description='厨房与餐桌区';
MERGE (sp:Spot {name:'八楼出租屋-床铺区'}) ON CREATE SET sp.id='R6YcFfBMWi', sp.kind='zone', sp.description='床铺区';
MERGE (sp:Spot {name:'八楼出租屋-进门处'}) ON CREATE SET sp.id='R6YcFfBMWj', sp.kind='zone', sp.description='进门玄关';
MERGE (sp:Spot {name:'星耀电竞基地-比赛馆区'}) ON CREATE SET sp.id='R6YcFfBMWk', sp.kind='zone', sp.description='比赛场馆（有赛/空场两版本）';
MERGE (sp:Spot {name:'星耀电竞基地-训练馆'}) ON CREATE SET sp.id='R6YcFfBMWl', sp.kind='zone', sp.description='二队训练馆';
MERGE (sp:Spot {name:'星耀电竞基地-经理办公区'}) ON CREATE SET sp.id='R6YcFfBMWm', sp.kind='zone', sp.description='经理办公区';
MERGE (sp:Spot {name:'星耀电竞基地-走廊'}) ON CREATE SET sp.id='R6YcFfBMWn', sp.kind='zone', sp.description='基地走廊';
MATCH (sp:Spot {id:'R6YcFfBMWZ'}), (l:Location {name:'长江大桥'}) MERGE (sp)-[r:part_of]->(l) ON CREATE SET r.sync=false;
MATCH (sp:Spot {id:'R6YcFfBMWa'}), (l:Location {name:'南滨路'}) MERGE (sp)-[r:part_of]->(l) ON CREATE SET r.sync=false;
MATCH (sp:Spot {id:'R6YcFfBMWb'}), (l:Location {name:'马路'}) MERGE (sp)-[r:part_of]->(l) ON CREATE SET r.sync=false;
MATCH (sp:Spot {id:'R6YcFfBMWc'}), (l:Location {name:'街角咖啡店'}) MERGE (sp)-[r:part_of]->(l) ON CREATE SET r.sync=false;
MATCH (sp:Spot {id:'R6YcFfBMWd'}), (l:Location {name:'酒店'}) MERGE (sp)-[r:part_of]->(l) ON CREATE SET r.sync=false;
MATCH (sp:Spot {id:'R6YcFfBMWe'}), (l:Location {name:'理发店'}) MERGE (sp)-[r:part_of]->(l) ON CREATE SET r.sync=false;
MATCH (sp:Spot {id:'R6YcFfBMWf'}), (l:Location {name:'连锁咖啡店'}) MERGE (sp)-[r:part_of]->(l) ON CREATE SET r.sync=false;
MATCH (sp:Spot {id:'R6YcFfBMWg'}), (l:Location {name:'八楼出租屋'}) MERGE (sp)-[r:part_of]->(l) ON CREATE SET r.sync=false;
MATCH (sp:Spot {id:'R6YcFfBMWh'}), (l:Location {name:'八楼出租屋'}) MERGE (sp)-[r:part_of]->(l) ON CREATE SET r.sync=false;
MATCH (sp:Spot {id:'R6YcFfBMWi'}), (l:Location {name:'八楼出租屋'}) MERGE (sp)-[r:part_of]->(l) ON CREATE SET r.sync=false;
MATCH (sp:Spot {id:'R6YcFfBMWj'}), (l:Location {name:'八楼出租屋'}) MERGE (sp)-[r:part_of]->(l) ON CREATE SET r.sync=false;
MATCH (sp:Spot {id:'R6YcFfBMWk'}), (l:Location {name:'星耀电竞基地'}) MERGE (sp)-[r:part_of]->(l) ON CREATE SET r.sync=false;
MATCH (sp:Spot {id:'R6YcFfBMWl'}), (l:Location {name:'星耀电竞基地'}) MERGE (sp)-[r:part_of]->(l) ON CREATE SET r.sync=false;
MATCH (sp:Spot {id:'R6YcFfBMWm'}), (l:Location {name:'星耀电竞基地'}) MERGE (sp)-[r:part_of]->(l) ON CREATE SET r.sync=false;
MATCH (sp:Spot {id:'R6YcFfBMWn'}), (l:Location {name:'星耀电竞基地'}) MERGE (sp)-[r:part_of]->(l) ON CREATE SET r.sync=false;
